controller_joint_names: ['', 'left_rover_side', 'tri_1', 'tri1_top', 'tri1_right', 'tri1_left', 'left_1', 'left_2', 'right_rover_side', 'tri_2', 'tri2_top', 'tri2_right', 'tri2_left', 'right_1', 'right_2', ]
